//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerson
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> Age { get; set; }
        public string City { get; set; }
        public Nullable<int> salary { get; set; }
    
        public virtual tblGender tblGender { get; set; }
    }
}
